[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_DEPLOY_TARGET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200